import { Template } from "./types";

export const PREBUILT_TEMPLATES: Template[] = [
  // 1. SaaS - CloudScale AI (Glassmorphism & Electric Indigo)
  {
    id: "tmpl-saas-cloudscale",
    name: "CloudScale AI",
    category: "SaaS",
    description: "High-converting dark glassmorphism landing page for cloud infrastructure and AI developer tools.",
    style: "Glassmorphism",
    thumbnailUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80",
    websiteData: {
      businessName: "CloudScale AI",
      tagline: "Autonomous Cloud Infrastructure Orchestration",
      description: "Scale distributed GPU workloads and serverless clusters across multi-cloud regions with zero config.",
      targetAudience: "Engineering teams, DevOps architects, and AI researchers",
      websiteType: "SaaS",
      theme: {
        colorTheme: "Electric Indigo",
        fontFamily: "Plus Jakarta Sans",
        borderRadius: "lg",
        animation: "Modern",
        style: "Glassmorphism",
      },
      sections: [
        {
          id: "cs-hero",
          type: "Hero",
          variant: "Modern Glass",
          badge: "Announcing CloudScale 3.0 with GPU Auto-tuning",
          title: "Scale Cloud Workloads With Autonomous AI",
          subtitle: "Deploy, monitor, and optimize your cloud instances automatically. Reduce AWS & GCP cloud spend by up to 48% with predictive capacity scaling.",
          ctaText: "Start Building Free",
          ctaLink: "#pricing",
          secondaryCtaText: "Read Technical Whitepaper",
          secondaryCtaLink: "#features",
          imageUrl: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=900&auto=format&fit=crop&q=80",
          items: [
            { title: "48%", description: "Average Cloud Bill Reduction" },
            { title: "99.999%", description: "Multi-region SLA Uptime" },
            { title: "< 1ms", description: "Edge Router Overhead" },
          ],
        },
        {
          id: "cs-features",
          type: "Features",
          variant: "Bento Box",
          badge: "Built for Mission-Critical Production",
          title: "Intelligent Infrastructure Without the Chaos",
          subtitle: "Everything modern DevOps and platform teams need to run compute at planet scale.",
          items: [
            {
              id: "csf-1",
              title: "GPU Spot Auto-Failover",
              description: "Zero-downtime hot migration across regions whenever spot compute nodes are recalled.",
              icon: "Cpu",
            },
            {
              id: "csf-2",
              title: "Predictive Autoscaling",
              description: "Machine-learning traffic forecasting scales cluster capacity 2 minutes before traffic spikes hit.",
              icon: "TrendingUp",
            },
            {
              id: "csf-3",
              title: "Universal Telemetry",
              description: "Real-time metrics, OpenTelemetry traces, and distributed logs visualized in one pane.",
              icon: "Activity",
            },
            {
              id: "csf-4",
              title: "Zero-Trust Mesh",
              description: "Automated mutual TLS encryption, short-lived tokens, and strict microsegmentation by default.",
              icon: "Shield",
            },
          ],
        },
        {
          id: "cs-pricing",
          type: "Pricing",
          variant: "Cards",
          badge: "Predictable Pricing",
          title: "Simple, Transparent Infrastructure Plans",
          subtitle: "Scale your compute with confidence. No opaque per-seat penalties.",
          items: [
            {
              id: "csp-1",
              title: "Developer",
              price: "$49",
              period: "/mo",
              description: "For early stage startups and staging test environments.",
              popular: false,
              features: ["Up to 10 nodes", "2 multi-cloud regions", "Community support", "Basic metric storage"],
              buttonText: "Deploy Free Sandbox",
            },
            {
              id: "csp-2",
              title: "Growth",
              price: "$199",
              period: "/mo",
              description: "The gold standard for high-growth tech companies.",
              popular: true,
              features: ["Up to 200 nodes", "All global regions", "Sub-minute auto-tuning", "24/7 Slack engineers"],
              buttonText: "Start 14-Day Pro Trial",
            },
            {
              id: "csp-3",
              title: "Enterprise",
              price: "$599",
              period: "/mo",
              description: "Dedicated clusters, VPC peering, and customized SLA.",
              popular: false,
              features: ["Unlimited nodes", "Dedicated TAM", "99.999% SLA guarantee", "Custom hardware isolation"],
              buttonText: "Schedule Architecture Call",
            },
          ],
        },
        {
          id: "cs-cta",
          type: "CTA",
          variant: "Centered",
          badge: "Get Started In 60 Seconds",
          title: "Stop Overpaying for Idle Cloud Servers",
          subtitle: "Connect your AWS, GCP, or Azure account in three CLI commands and see instant savings.",
          ctaText: "Get Started Free",
          ctaLink: "#pricing",
          secondaryCtaText: "Talk to Solutions Architect",
          secondaryCtaLink: "#contact",
        },
        {
          id: "cs-footer",
          type: "Footer",
          title: "CloudScale AI",
          description: "Autonomous cloud capacity orchestration for forward-thinking engineering organizations.",
        },
      ],
      seo: {
        title: "CloudScale AI — Autonomous Cloud Infrastructure Orchestration",
        metaDescription: "Scale GPU workloads and reduce cloud spend by up to 48% with predictive AI capacity scaling.",
        keywords: ["Cloud Infrastructure", "Kubernetes", "DevOps", "AI Cloud"],
      },
    },
  },

  // 2. SaaS - SaaSFlow Metrics (Modern & Ocean Azure)
  {
    id: "tmpl-saas-saasflow",
    name: "SaaSFlow Metrics",
    category: "SaaS",
    description: "Sleek modern analytics and MRR cohort visualization dashboard landing page.",
    style: "Modern",
    thumbnailUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80",
    websiteData: {
      businessName: "SaaSFlow Metrics",
      tagline: "Subscription Revenue Intelligence for Founders",
      description: "Real-time MRR tracking, churn prediction, and subscriber lifetime value analytics.",
      targetAudience: "B2B SaaS founders, finance executives, and product leaders",
      websiteType: "SaaS",
      theme: {
        colorTheme: "Ocean Azure",
        fontFamily: "Inter",
        borderRadius: "md",
        animation: "Subtle",
        style: "Modern",
      },
      sections: [
        {
          id: "sf-hero",
          type: "Hero",
          variant: "Split / Two Column",
          badge: "Revenue Intelligence Platform",
          title: "Know Exactly Where Your Revenue Is Flowing",
          subtitle: "SaaSFlow connects with Stripe, Paddle, and Chargebee to deliver crystal-clear cohort retention, expansion MRR, and predictive churn analytics in real time.",
          ctaText: "Connect Your Billing Account",
          ctaLink: "#pricing",
          secondaryCtaText: "Explore Interactive Demo",
          secondaryCtaLink: "#features",
          imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=900&auto=format&fit=crop&q=80",
          items: [
            { title: "$1.2B+", description: "Tracked Annual Run-rate" },
            { title: "1,400+", description: "SaaS Companies Onboarded" },
            { title: "99.4%", description: "Churn Forecast Accuracy" },
          ],
        },
        {
          id: "sf-features",
          type: "Features",
          variant: "Grid",
          badge: "Unrivaled Clarity",
          title: "Stop Guessing Your Growth Levers",
          subtitle: "Drill down into any subscriber cohort with sub-second queries and automated executive summaries.",
          items: [
            { id: "sff-1", title: "Smart Churn Early Warning", description: "Identifies usage drops 30 days before cancellations happen so your team can intervene.", icon: "AlertTriangle" },
            { id: "sff-2", title: "Automated LTV:CAC Ratios", description: "Blends attribution spend with stripe revenue to reveal your most profitable acquisition channels.", icon: "PieChart" },
            { id: "sff-3", title: "Real-time Slack Alerts", description: "Celebrate new upgrades, large expansions, and monitor failed cards directly in your team channels.", icon: "Bell" },
          ],
        },
        {
          id: "sf-testimonials",
          type: "Testimonials",
          variant: "Single Focus",
          badge: "Founder Testimonials",
          title: "Trusted by Fast-Growing SaaS Brands",
          items: [
            {
              id: "sft-1",
              title: "Invaluable for Board Meetings",
              description: "SaaSFlow became our single source of truth within 24 hours. The cohort retention charts alone saved our Series A pitch.",
              author: "Miriam Hoffman",
              role: "Co-Founder & CEO, HyperScale",
              avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80",
            },
          ],
        },
        {
          id: "sf-pricing",
          type: "Pricing",
          variant: "Cards",
          badge: "Fair Scaled Pricing",
          title: "Priced by Tracked Revenue",
          items: [
            { id: "sfp-1", title: "Seed", price: "$39", period: "/mo", description: "Up to $25k MRR", features: ["Full cohort analytics", "1 Stripe account", "Email support"] },
            { id: "sfp-2", title: "Growth", price: "$99", period: "/mo", popular: true, description: "Up to $100k MRR", features: ["Unlimited payment gateways", "Slack alerts", "Benchmark comparison"] },
          ],
        },
        { id: "sf-footer", type: "Footer", title: "SaaSFlow Metrics", description: "The definitive subscription financial intelligence suite." },
      ],
      seo: {
        title: "SaaSFlow Metrics — Subscription Revenue Intelligence",
        metaDescription: "Real-time MRR tracking, churn prediction, and subscriber lifetime value analytics.",
        keywords: ["SaaS Metrics", "MRR", "Stripe Analytics", "Churn Prevention"],
      },
    },
  },

  // 3. SaaS - DevPulse API (Dark & Cyberpunk Neon)
  {
    id: "tmpl-saas-devpulse",
    name: "DevPulse API",
    category: "SaaS",
    description: "High-tech cyberpunk developer platform for API observability and distributed tracing.",
    style: "Dark",
    thumbnailUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80",
    websiteData: {
      businessName: "DevPulse API",
      tagline: "Ultra-low Latency API Gateway & Tracing",
      description: "Inspect API payloads, enforce global rate limits, and generate mock services in milliseconds.",
      targetAudience: "Backend developers, platform engineers, and API architects",
      websiteType: "SaaS",
      theme: {
        colorTheme: "Cyberpunk Neon",
        fontFamily: "Space Grotesk",
        borderRadius: "sm",
        animation: "Modern",
        style: "Dark",
      },
      sections: [
        {
          id: "dp-hero",
          type: "Hero",
          variant: "Headline Focus",
          badge: "Developer Preview — 0.2ms Edge Overhead",
          title: "Supercharge Your APIs With Zero Friction",
          subtitle: "Universal gateway with built-in token auth, rate limiting, and instant OpenTelemetry instrumentation for modern microservices.",
          ctaText: "Read the Docs",
          ctaLink: "#features",
          secondaryCtaText: "Deploy in 1 Command",
          secondaryCtaLink: "#pricing",
          imageUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=900&auto=format&fit=crop&q=80",
        },
        {
          id: "dp-features",
          type: "Features",
          variant: "Columns",
          badge: "Edge Architecture",
          title: "Speed Meets Unbreakable Reliability",
          subtitle: "Designed to handle millions of requests per second without a single frame dropped.",
          items: [
            { id: "dpf-1", title: "Distributed Token Buckets", description: "Synchronize rate-limiting across 300+ edge cities without bottlenecking centralized databases.", icon: "Layers" },
            { id: "dpf-2", title: "GraphQL & REST Inspector", description: "Live payload diffing, query cost analysis, and automatic anomaly alerting in real-time.", icon: "Code" },
          ],
        },
        {
          id: "dp-pricing",
          type: "Pricing",
          variant: "Cards",
          badge: "Developer Tier Included",
          title: "Pay Only For Traced Requests",
          items: [
            { id: "dpp-1", title: "Free Tier", price: "$0", period: "/mo", description: "1 Million requests/mo", features: ["5 Edge locations", "24h Log retention", "Community Discord"] },
            { id: "dpp-2", title: "Pro Gateway", price: "$79", period: "/mo", popular: true, description: "10 Million requests/mo", features: ["Global 300+ edge cities", "30-day tracing retention", "Webhooks & Alerting"] },
          ],
        },
        { id: "dp-footer", type: "Footer", title: "DevPulse API", description: "The next-generation edge API routing layer." },
      ],
      seo: { title: "DevPulse API — Edge API Gateway & Tracing", metaDescription: "Inspect payloads and enforce global rate limits.", keywords: ["API Gateway", "Developer Tools"] },
    },
  },

  // 4. Portfolio - Alex Rivera Creative (Minimal & Monochrome Minimal)
  {
    id: "tmpl-portfolio-alex",
    name: "Alex Rivera Creative",
    category: "Portfolio",
    description: "Minimalist, editorial-style personal portfolio for product designers and art directors.",
    style: "Minimal",
    thumbnailUrl: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=600&auto=format&fit=crop&q=80",
    websiteData: {
      businessName: "Alex Rivera",
      tagline: "Digital Product Designer & Creative Technologist",
      description: "Crafting thoughtful digital interfaces, design systems, and brand identities for world-class tech companies.",
      targetAudience: "Design directors, venture-backed founders, and design studios",
      websiteType: "Portfolio",
      theme: {
        colorTheme: "Monochrome Minimal",
        fontFamily: "Inter",
        borderRadius: "none",
        animation: "Subtle",
        style: "Minimal",
      },
      sections: [
        {
          id: "ar-hero",
          type: "Hero",
          variant: "Minimal",
          badge: "Currently Available for Select Projects — Q3/Q4",
          title: "Designing Digital Experiences That Inspire and Endure",
          subtitle: "Over 8 years bridging the gap between human emotion, visual elegance, and engineering craftsmanship.",
          ctaText: "View Featured Work",
          ctaLink: "#about",
          secondaryCtaText: "Get in Touch",
          secondaryCtaLink: "#contact",
          imageUrl: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=900&auto=format&fit=crop&q=80",
          items: [
            { title: "8+ Years", description: "Design Leadership" },
            { title: "24 Awards", description: "Awwwards & FWA" },
            { title: "12M+ Users", description: "Touched by Shipped Work" },
          ],
        },
        {
          id: "ar-about",
          type: "About",
          variant: "Minimal",
          badge: "Selected Philosophy",
          title: "Simplicity is the Ultimate Sophistication",
          description: "I believe great design is not about what you add, but what you take away until only pure utility and quiet beauty remain.",
          imageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=900&auto=format&fit=crop&q=80",
          items: [
            { title: "Design Systems", description: "Scalable Figma component architectures built for velocity." },
            { title: "Prototyping", description: "Micro-interactions and motion design that feel organic." },
          ],
        },
        {
          id: "ar-contact",
          type: "Contact",
          badge: "Let's Collaborate",
          title: "Have an Ambitious Project in Mind?",
          subtitle: "Drop me an email or schedule a quick 15-minute introductory video call.",
          description: "Open for full-cycle product design, advisory, and creative direction.",
          items: [
            { title: "Email", description: "alex@riveradesign.studio" },
            { title: "Location", description: "Berlin • New York" },
          ],
        },
        { id: "ar-footer", type: "Footer", title: "Alex Rivera", description: "Crafted with precision. All rights reserved." },
      ],
      seo: { title: "Alex Rivera — Product Designer Portfolio", metaDescription: "Portfolio of Alex Rivera, Digital Product Designer.", keywords: ["Product Designer", "Portfolio", "UI/UX"] },
    },
  },

  // 5. Portfolio - DevStudio Showcase (Dark & Emerald Slate)
  {
    id: "tmpl-portfolio-devstudio",
    name: "DevStudio Showcase",
    category: "Portfolio",
    description: "Bold dark-themed portfolio for full-stack engineers and indie hackers.",
    style: "Dark",
    thumbnailUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80",
    websiteData: {
      businessName: "DevStudio Showcase",
      tagline: "Full Stack Engineer & OSS Contributor",
      description: "Specializing in distributed systems, Next.js web applications, and high-performance WebGL graphics.",
      targetAudience: "Engineering managers, recruiters, and tech founders",
      websiteType: "Portfolio",
      theme: {
        colorTheme: "Emerald Slate",
        fontFamily: "Space Grotesk",
        borderRadius: "md",
        animation: "Modern",
        style: "Dark",
      },
      sections: [
        {
          id: "ds-hero",
          type: "Hero",
          variant: "Split / Two Column",
          badge: "Open Source Advocate",
          title: "Building Resilient Software at the Edge",
          subtitle: "Senior engineer shipping clean code, robust backend architectures, and delightful interactive user experiences.",
          ctaText: "Check My Repos",
          ctaLink: "#features",
          secondaryCtaText: "Download Resume",
          secondaryCtaLink: "#contact",
          imageUrl: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=900&auto=format&fit=crop&q=80",
        },
        {
          id: "ds-features",
          type: "Features",
          variant: "Bento Box",
          badge: "Technical Expertise",
          title: "Core Engineering Stack",
          subtitle: "From low-level microservices to responsive frontend animation.",
          items: [
            { id: "dsf-1", title: "Distributed Cloud Architecture", description: "Designing serverless stateful pipelines with Redis and PostgreSQL.", icon: "Server" },
            { id: "dsf-2", title: "High-FPS Canvas & WebGL", description: "Interactive 3D graphics rendering in Three.js and WebGL shaders.", icon: "Box" },
          ],
        },
        { id: "ds-footer", type: "Footer", title: "DevStudio Showcase", description: "Code is poetry executed at the speed of silicon." },
      ],
      seo: { title: "DevStudio Showcase — Full Stack Engineer Portfolio", metaDescription: "Full stack engineering portfolio.", keywords: ["Full Stack", "Developer"] },
    },
  },

  // 6. Agency - Apex Growth Digital (Modern & Sunset Amber)
  {
    id: "tmpl-agency-apex",
    name: "Apex Growth Digital",
    category: "Agency",
    description: "High-energy, conversion-focused digital marketing and growth agency landing page.",
    style: "Modern",
    thumbnailUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&auto=format&fit=crop&q=80",
    websiteData: {
      businessName: "Apex Growth Digital",
      tagline: "Performance Marketing & Brand Acceleration",
      description: "We help venture-backed brands scale revenue through paid acquisition, conversion rate optimization, and viral creative campaigns.",
      targetAudience: "CMOs, eCommerce founders, and VC portfolio companies",
      websiteType: "Agency",
      theme: {
        colorTheme: "Sunset Amber",
        fontFamily: "Plus Jakarta Sans",
        borderRadius: "lg",
        animation: "Modern",
        style: "Modern",
      },
      sections: [
        {
          id: "ag-hero",
          type: "Hero",
          variant: "Centered",
          badge: "Over $180M in Client Revenue Generated",
          title: "We Turn Ad Spend Into Unstoppable Revenue",
          subtitle: "Tired of cookie-cutter agencies that report vanity metrics? We engineer predictable, ROAS-driven acquisition engines.",
          ctaText: "Claim Your Free Growth Audit",
          ctaLink: "#contact",
          secondaryCtaText: "See Client Case Studies",
          secondaryCtaLink: "#testimonials",
          imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=900&auto=format&fit=crop&q=80",
          items: [
            { title: "4.8x", description: "Average Client ROAS" },
            { title: "35+", description: "In-House Growth Specialists" },
            { title: "$180M+", description: "Tracked Revenue Generated" },
          ],
        },
        {
          id: "ag-features",
          type: "Features",
          variant: "Grid",
          badge: "Full-Funnel Mastery",
          title: "Our Proven 3-Pillar Growth Engine",
          items: [
            { id: "agf-1", title: "Algorithmic Media Buying", description: "Deep creative testing and custom bidding scripts across Meta, TikTok, and Google Ads.", icon: "Target" },
            { id: "agf-2", title: "High-Converting Landers", description: "Custom dynamic landing pages tailored per ad audience to multiply conversion rates.", icon: "Layout" },
            { id: "agf-3", title: "Lifecycle Retention", description: "SMS and email automation sequences that extract maximum lifetime value from every customer.", icon: "Mail" },
          ],
        },
        {
          id: "ag-testimonials",
          type: "Testimonials",
          variant: "Grid",
          badge: "Proven Results",
          title: "What Our Partners Say",
          items: [
            {
              id: "agt-1",
              title: "Tripled Our Monthly Revenue",
              description: "Apex Growth came in and audited our entire funnel. Within 90 days our customer acquisition cost dropped by 42% while scaling spend.",
              author: "Jason Cole",
              role: "Head of Growth, Lumina Goods",
              avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
            },
          ],
        },
        { id: "ag-footer", type: "Footer", title: "Apex Growth Digital", description: "Precision growth marketing for visionary brands." },
      ],
      seo: { title: "Apex Growth Digital — Performance Marketing Agency", metaDescription: "Scale revenue through paid acquisition and CRO.", keywords: ["Growth Agency", "Performance Marketing"] },
    },
  },

  // 7. Agency - Vanguard Creative Agency (Luxury & Rose Quartz)
  {
    id: "tmpl-agency-vanguard",
    name: "Vanguard Creative",
    category: "Agency",
    description: "Ultra-luxury branding and 3D motion design agency landing page.",
    style: "Luxury",
    thumbnailUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80",
    websiteData: {
      businessName: "Vanguard Creative",
      tagline: "Bespoke Brand Strategy & Cinematic Motion",
      description: "We craft iconic visual identities and cinematic digital storytelling for prestigious luxury brands.",
      targetAudience: "Luxury houses, boutique hospitality, and architectural firms",
      websiteType: "Agency",
      theme: {
        colorTheme: "Rose Quartz",
        fontFamily: "Playfair Display",
        borderRadius: "sm",
        animation: "Subtle",
        style: "Luxury",
      },
      sections: [
        {
          id: "vg-hero",
          type: "Hero",
          variant: "Minimal",
          badge: "Maison de Création",
          title: "Where Artistry Meets Timeless Distinction",
          subtitle: "We forge unforgettable brand narratives through bespoke typography, architectural aesthetics, and evocative digital craftsmanship.",
          ctaText: "Request Private Portfolio",
          ctaLink: "#contact",
          imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop&q=80",
        },
        { id: "vg-footer", type: "Footer", title: "Vanguard Creative", description: "Paris • New York • Tokyo" },
      ],
      seo: { title: "Vanguard Creative — Luxury Branding Studio", metaDescription: "Bespoke brand strategy and cinematic motion.", keywords: ["Luxury Studio", "Creative Agency"] },
    },
  },

  // 8. Restaurant - L'Aura Bistro & Bar (Luxury & Sunset Amber)
  {
    id: "tmpl-restaurant-laura",
    name: "L'Aura Bistro & Bar",
    category: "Restaurant",
    description: "Refined, romantic French-Mediterranean bistro landing page with reservation CTA.",
    style: "Luxury",
    thumbnailUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&auto=format&fit=crop&q=80",
    websiteData: {
      businessName: "L'Aura Bistro & Bar",
      tagline: "Modern French-Mediterranean Gastronomy",
      description: "An intimate culinary sanctuary pairing seasonal farm-fresh harvests with an extensive natural wine cellar.",
      targetAudience: "Culinary enthusiasts, romantic dinner guests, and private event hosts",
      websiteType: "Restaurant",
      theme: {
        colorTheme: "Sunset Amber",
        fontFamily: "Playfair Display",
        borderRadius: "sm",
        animation: "Subtle",
        style: "Luxury",
      },
      sections: [
        {
          id: "la-hero",
          type: "Hero",
          variant: "Centered",
          badge: "Michelin Guide Selected 2025",
          title: "An Unforgettable Culinary Journey in the Heart of the City",
          subtitle: "Chef Laurent Dubois presents an innovative tasting menu celebrating organic coastal flavors and artisanal heritage.",
          ctaText: "Reserve Your Table",
          ctaLink: "#contact",
          secondaryCtaText: "Explore Seasonal Menu",
          secondaryCtaLink: "#about",
          imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=900&auto=format&fit=crop&q=80",
          items: [
            { title: "Farm to Table", description: "100% Seasonal Local Ingredients" },
            { title: "350+ Labels", description: "Curated Natural Wine Selection" },
            { title: "Private Dining", description: "Available for up to 32 guests" },
          ],
        },
        {
          id: "la-about",
          type: "About",
          variant: "Split",
          badge: "The Culinary Philosophy",
          title: "Rooted in Passion, Elevated by Technique",
          description: "Every plate is a tribute to the vibrant terroir of Provence and the Mediterranean coast, curated with obsessive reverence for simple, honest flavors.",
          imageUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=900&auto=format&fit=crop&q=80",
          items: [
            { title: "Handmade Daily", description: "Fresh breads, cultured butter, and delicate pastas created every morning." },
            { title: "Sommelier Pairings", description: "Expertly matched vintages to illuminate each course." },
          ],
        },
        {
          id: "la-contact",
          type: "Contact",
          badge: "Reservations & Hours",
          title: "Join Us for an Evening of Indulgence",
          subtitle: "Tables are released 30 days in advance. Walk-ins welcomed at the cocktail bar.",
          description: "Dinner served Tuesday through Sunday from 5:30 PM to 11:00 PM.",
          items: [
            { title: "Location", description: "428 Mercer Street, SoHo, NY" },
            { title: "Telephone", description: "+1 (212) 555-0194" },
            { title: "Dress Code", description: "Smart Casual" },
          ],
        },
        { id: "la-footer", type: "Footer", title: "L'Aura Bistro", description: "Warm hospitality, unforgettable flavors." },
      ],
      seo: { title: "L'Aura Bistro & Bar — French-Mediterranean Dining", metaDescription: "An intimate culinary sanctuary in SoHo.", keywords: ["Bistro", "Fine Dining", "Reservations"] },
    },
  },

  // 9. Restaurant - Artisan Wood Fired Pizza (Modern & Rose Quartz)
  {
    id: "tmpl-restaurant-pizza",
    name: "Artisan Wood Fired Pizza",
    category: "Restaurant",
    description: "Vibrant rustic Neapolitan pizzeria landing page with delivery ordering and events.",
    style: "Modern",
    thumbnailUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80",
    websiteData: {
      businessName: "Forno Antico Pizza",
      tagline: "Authentic Neapolitan Sourdough Pizza",
      description: "Fermented for 72 hours and blistered at 900 degrees in our custom hand-built volcanic stone ovens.",
      targetAudience: "Pizza lovers, families, craft beer aficionados",
      websiteType: "Restaurant",
      theme: {
        colorTheme: "Rose Quartz",
        fontFamily: "Outfit",
        borderRadius: "lg",
        animation: "Subtle",
        style: "Modern",
      },
      sections: [
        {
          id: "pz-hero",
          type: "Hero",
          variant: "Split / Two Column",
          badge: "72-Hour Naturally Fermented Dough",
          title: "Pure Neapolitan Tradition, Blistered to Perfection",
          subtitle: "San Marzano tomatoes, buffalo mozzarella imported weekly from Campania, and charred blistered crust that melts in your mouth.",
          ctaText: "Order Online for Pickup",
          ctaLink: "#contact",
          imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=900&auto=format&fit=crop&q=80",
        },
        { id: "pz-footer", type: "Footer", title: "Forno Antico Pizza", description: "Napoli spirit, neighborhood warmth." },
      ],
      seo: { title: "Forno Antico — Authentic Neapolitan Pizza", metaDescription: "Wood-fired Neapolitan sourdough pizza.", keywords: ["Pizza", "Wood Fired"] },
    },
  },

  // 10. Startup - HyperLoop Logistics (Dark & Electric Indigo)
  {
    id: "tmpl-startup-hyperloop",
    name: "HyperLoop Logistics",
    category: "Startup",
    description: "Futuristic pitch-ready landing page for clean tech & next-gen autonomous freight startup.",
    style: "Dark",
    thumbnailUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&auto=format&fit=crop&q=80",
    websiteData: {
      businessName: "HyperLoop Freight",
      tagline: "Zero-Emission Autonomous Intercity Freight",
      description: "Electrifying intermodal transit corridors with automated sub-surface vacuum tube shuttles.",
      targetAudience: "Supply chain executives, venture capital, and municipal planners",
      websiteType: "Startup",
      theme: {
        colorTheme: "Electric Indigo",
        fontFamily: "Space Grotesk",
        borderRadius: "md",
        animation: "Modern",
        style: "Dark",
      },
      sections: [
        {
          id: "hl-hero",
          type: "Hero",
          variant: "Headline Focus",
          badge: "Series A Funded • $35M Raised",
          title: "The Zero-Carbon Hyper-Speed Logistics Network",
          subtitle: "Moving cargo 5x faster than freight trucks at 70% lower energy cost. Welcome to the future of continent-wide supply chains.",
          ctaText: "Explore the Corridors",
          ctaLink: "#about",
          secondaryCtaText: "Join the Waitlist",
          secondaryCtaLink: "#contact",
          imageUrl: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=900&auto=format&fit=crop&q=80",
        },
        {
          id: "hl-features",
          type: "Features",
          variant: "Bento Box",
          badge: "Breakthrough Physics",
          title: "Engineered for Exponential Velocity",
          items: [
            { id: "hlf-1", title: "Magnetic Levitation", description: "Frictionless glide at 600+ km/h through low-pressure sealed tubes.", icon: "Zap" },
            { id: "hlf-2", title: "Solar Microgrid Powered", description: "Tubular solar arrays produce 120% of required operating energy.", icon: "Sun" },
          ],
        },
        { id: "hl-footer", type: "Footer", title: "HyperLoop Freight", description: "Accelerating global commerce cleanly." },
      ],
      seo: { title: "HyperLoop Freight — Zero-Emission Logistics", metaDescription: "Automated sub-surface cargo shuttles.", keywords: ["Logistics", "Autonomous", "CleanTech"] },
    },
  },

  // 11. Startup - BioSync Wearables (Glassmorphism & Emerald Slate)
  {
    id: "tmpl-startup-biosync",
    name: "BioSync Wearables",
    category: "Startup",
    description: "Sleek biometric hardware and AI health longevity tracker landing page.",
    style: "Glassmorphism",
    thumbnailUrl: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=600&auto=format&fit=crop&q=80",
    websiteData: {
      businessName: "BioSync Health",
      tagline: "Continuous Molecular Longevity Monitoring",
      description: "The first continuous metabolic biosensor that maps glucose, cortisol, and cellular recovery in real time.",
      targetAudience: "Biohackers, endurance athletes, and preventive health enthusiasts",
      websiteType: "Startup",
      theme: {
        colorTheme: "Emerald Slate",
        fontFamily: "Outfit",
        borderRadius: "full",
        animation: "Modern",
        style: "Glassmorphism",
      },
      sections: [
        {
          id: "bs-hero",
          type: "Hero",
          variant: "Modern Glass",
          badge: "Clinical Precision Bio-Telemetry",
          title: "Decode Your Biology Before Symptoms Emerge",
          subtitle: "BioSync monitors cellular stress and hormonal balance 24/7. Turn metabolic data into actionable daily longevity protocols.",
          ctaText: "Pre-order Member Kit",
          ctaLink: "#pricing",
          imageUrl: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=900&auto=format&fit=crop&q=80",
        },
        { id: "bs-footer", type: "Footer", title: "BioSync Health", description: "Live longer, perform better." },
      ],
      seo: { title: "BioSync Health — Continuous Longevity Wearable", metaDescription: "Continuous metabolic biosensor.", keywords: ["Wearable", "Longevity", "Health"] },
    },
  },

  // 12. AI Tool - NeuroCanvas AI (Neon & Royal Purple)
  {
    id: "tmpl-aitool-neurocanvas",
    name: "NeuroCanvas AI",
    category: "AI Tool",
    description: "Futuristic neon landing page for generative AI design and video creation studio.",
    style: "Neon",
    thumbnailUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80",
    websiteData: {
      businessName: "NeuroCanvas AI",
      tagline: "Generative Multimodal Canvas for Designers",
      description: "Generate 4K cinematic video, 3D textures, and responsive UI components directly on an infinite collaborative canvas.",
      targetAudience: "Game designers, VFX artists, and creative agencies",
      websiteType: "AI Tool",
      theme: {
        colorTheme: "Royal Purple",
        fontFamily: "Space Grotesk",
        borderRadius: "md",
        animation: "Modern",
        style: "Neon",
      },
      sections: [
        {
          id: "nc-hero",
          type: "Hero",
          variant: "Centered",
          badge: "NeuroCanvas v2 Released",
          title: "Turn Prompts Into Cinematic Realities in Real Time",
          subtitle: "The all-in-one generative studio powered by diffusion transformers. Create concept art, motion graphics, and voice in one unified space.",
          ctaText: "Try in Browser Free",
          ctaLink: "#pricing",
          imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=900&auto=format&fit=crop&q=80",
        },
        { id: "nc-footer", type: "Footer", title: "NeuroCanvas AI", description: "Unleashing the infinite imagination." },
      ],
      seo: { title: "NeuroCanvas AI — Generative Canvas", metaDescription: "Multimodal generative AI studio.", keywords: ["AI Tool", "Generative AI"] },
    },
  },
];
